<!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top col-lg-12 col-md-12 col-sm-12 col-xs-12 pull-right" style="">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="true" aria-controls="navbar" style="float: right">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="index.php" title="خانه"><i class="fa fa-home"></i></a></li>
            <li><a href="search.php" title="جست و جو"><i class="fa fa-search"></i></a></li>
            <!--<li><a href="register.php">ثبت نام</a></li> -->
            <li><a href="ads-register.php">تبلیغات</a></li>
		      <li><a href="aboutus.php" title="سوالات رایج"><i class="fa fa-question"></i></a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
